---
- name: Set custom fact for ansible_user
  set_fact:
    ansible_user: "{{ lookup('env', 'USER') }}"

- name: Install packages
  become: true
  community.general.pacman:
    update_cache: yes
    name:
      - zsh
      - tmux
      - kitty
      - neovim
      - fzf
      - zoxide
      - xclip
      - otf-comicshanns-nerd
    state: present

- name: Setup
  script: setup.sh 

- name: Check if Tmux Plugin Manager repo exists
  stat:
    path: "{{ ansible_user_dir }}/.tmux/plugins/tpm"
  register: tpm_installed

- name: Clone Tmux Plugin Manager repo
  command: git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  when: tpm_installed.stat.exists == False

- name: Install custom NvChad
  command: git clone https://github.com/R8Sec/custom-nvchad.git ~/.config/nvim

- name: Copy .zshrc
  copy:
    src: ".zshrc"
    dest: "{{ ansible_user_dir }}/.zshrc"
    force: yes

- name: Copy .tmux.conf
  copy:
    src: ".tmux.conf"
    dest: "{{ ansible_user_dir }}/.tmux.conf"
    force: yes

- name: create kitty dir
  file:
    path: "{{ ansible_user_dir }}/.config/kitty"
    state: directory

- name: Copy kitty.conf
  copy:
    src: "kitty.conf"
    dest: "{{ ansible_user_dir }}/.config/kitty/kitty.conf"
    force: yes

- name: Change default shell to zsh
  become: True
  user:
    name: "{{ ansible_user }}"
    shell: /bin/zsh
  when: ansible_user != 'root'
