---
- name: Dependencies
  become: True
  community.general.pacman:
    update_cache: yes
    name:
      - git
      - base-devel

- name: Paru
  become: True
  script: paru.sh

- name: BlackArch
  become: True
  script: blackarch.s
