---
packages_to_install:
  - openvpn
  - wireguard-tools
  - python-pipx
  - jq
  - flameshot
  - pandoc
  - feh
  - bloodhound
  - bloodhound-python
  - seclists
  - eyewitness
  - cupp
  - smtp-user-enum
  - xxd
  - openldap
  - ghidra
  - nmap
  - wireshark-qt
  - wireshark-cli
  - tcpdump
  - burpsuite
  - metasploit
  - sqlmap
  - john
  - impacket
  - crackmapexec

python_packages:
  - pwntools
